name: Save daily leaderboard

on:
  schedule:
    - cron: '0 5 * * *' # At 05:OO UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4.1.1 # checkout the repository content
        with:
          ref: dataviz

      - name: setup python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.11' # install the python version needed

      - name: execute py script # run extractLeaderboard.py
        env:
          aocLeaderboardId: ${{ secrets.AOCLEADERBOARDID }}
          aocSession: ${{ secrets.AOCSESSION }}
        run: python datavize/extractLeaderboard.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
