name: Save daily leaderboard

on:
  schedule:
    - cron: '50 4 * * *' # At 04:55 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4.1.1 # checkout the repository content
        with:
          ref: dataviz

      - name: setup python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.11' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r dataviz/requirements.txt

      - name: execute extractLeaderboard py script # run extractLeaderboard.py
        env:
          aocLeaderboardId: ${{ secrets.AOCLEADERBOARDID }}
          aocSession: ${{ secrets.AOCSESSION }}
        run: python dataviz/extractLeaderboard.py

      - name: execute compareUsers py script # run compareUsers.py
        run: python dataviz/compareUsers.py

      - name: commit and push files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Daily leaderboard" --allow-empty)
          git push 
